### ISSUE TITLE
How to use sourcemaps?

### ISSUE THREAD

**Issue by lilliputten** [bem/bem-react-boilerplate#1]
I see that some maps are present, but what I see during debugging is not my source code. How I can to enable them properly?

**Comment by awinogradov** [comment]
Everything here works like in `create-bem-react-app`. Can you explain more details?

**Comment by lilliputten** [comment]
I see my source code in the state before merging in single bundle by webpack (individual modules -- it's ok), but after processing by babel (so it isn't my original code, but processed).

**Comment by awinogradov** [comment]
Ok, I understand. You need to check this file https://github.com/bem/bem-react-boilerplate/blob/master/config-overrides.js and check settings for babel source maps

**Comment by lilliputten** [comment]
Still can't find the right solution for passing sourcemaps from babel. %((

Tried (in config-overrides.js):

1. To add `devtool: 'source-map'`, `sourceMaps: true` (or `'inline'`) and `retainLines: true` in `options` extension (for `babelLoader.loader`).

2. To pass `sourceMaps: true` for es2015-plugin options.

3. To add `config = injectBabelPlugin('source-map-support', config)` in `override`.

All with no effect. What else should I try?

**Comment by lilliputten** [comment]
I see that my wish is almost impossible:

[Can I debug source code instead of compiled one? · Issue #343 · facebook/create-react-app](https://github.com/facebook/create-react-app/issues/343)
